export const LOGIN = '/login';
export const PROFILES = '/profiles'
export const NOTIFICATIONS = '/notifications';
export const SITES = '/sites';
export const OVERVIEW = '/overview';
export const DEFECT_SEVERITY = '/site_defects_severity';
export const ORGANIZATIONS = '/organizations';
export const DOCUMENTS = '/root_documents';
export const FOLDERS = '/folders';
export const FILES = '';
export const ANNOTATIONS = '/sites/{0}/annotations'
export const ANOMALY_TYPES ='/anomaly_types';
